//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : System.cpp
//  @ Date : 09.04.2024
//  @ Author :
//
//


#include "System.h"

bool System::authenticateUser(string tHaslo, string tID) {
    for(int i = 0; i < users.size(); i++){
        if(users[i]->getID() == tID && users[i]->getHaslo() == tHaslo){
            return true;
        }
    }
    return false;
}

void System::registerUser(string tHaslo, string tID) {
    User *user = new User();
    user->setHaslo(tHaslo);
    user->setID(tID);
    users.push_back(user);

}

