//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : System.h
//  @ Date : 09.04.2024
//  @ Author :
//
//


#if !defined(_SYSTEM_H)
#define _SYSTEM_H

#include <string>
#include <vector>
using namespace std;
class User;

class System {
public:
	bool authenticateUser(string tHaslo, string tID);
	void registerUser(string tHaslo, string tID);
private:
	vector<User*> users;
};

#endif  //_SYSTEM_H
