//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : User.cpp
//  @ Date : 09.04.2024
//  @ Author :
//
//


#include "User.h"

void User::setID(string tID) {
    ID = tID;
}

void User::setHaslo(string tHaslo) {
    Haslo = tHaslo;
}

string User::getID() {
    return ID;
}

string User::getHaslo() {
    return Haslo;
}

