//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TBiblioteka.h
//  @ Date : 05.04.2024
//  @ Author : 
//
//


#if !defined(_TBIBLIOTEKA_H)
#define _TBIBLIOTEKA_H


#include <vector>
#include <string>

class TKsiazka;

using namespace std;
class TBiblioteka {
public:
	void attach(TKsiazka* ksiazka);
	void detach();
	void printData(int i);
	void setData(int i, string tytul, string autor);
private:
	vector<TKsiazka*> ksiazki;
};

#endif  //_TBIBLIOTEKA_H
