//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TBiblioteka.cpp
//  @ Date : 05.04.2024
//  @ Author : 
//
//

#include "TKsiazka.h"
#include "TBiblioteka.h"
#include <iostream>
using namespace std;
void TBiblioteka::attach(TKsiazka* ksiazka) {
    ksiazki.push_back(ksiazka);
}

void TBiblioteka::detach() {
    ksiazki.pop_back();
}

void TBiblioteka::printData(int i) {
    cout << ksiazki[i]->getTytul() << " " << ksiazki[i]->getAutor() << endl;
}

void TBiblioteka::setData(int i, string tytul, string autor) {
    ksiazki[i]->setTytul(tytul);
    ksiazki[i]->setAutor(autor);
}

