//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TKsiazka.cpp
//  @ Date : 05.04.2024
//  @ Author : 
//
//


#include "TKsiazka.h"
#include <iostream>
#include "TStrona.h"
using namespace std;
TKsiazka::TKsiazka() {

}

TKsiazka::~TKsiazka() {

}

void TKsiazka::setTytul(string tTytul) {
    tytul = tTytul;
}

string TKsiazka::getTytul() {
    return tytul;
}

void TKsiazka::setAutor(string tAutor) {
    autor = tAutor;
}

string TKsiazka::getAutor() {
    return autor;
}

void TKsiazka::printData() {
    cout << strona->getNrStrony() << endl;
    cout << tytul << endl;
    cout << autor << endl;
}

void TKsiazka::setData(int tNrStrony) {
    strona->setNrStrony(tNrStrony);
}

