//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TKsiazka.h
//  @ Date : 05.04.2024
//  @ Author : 
//
//


#if !defined(_TKSIAZKA_H)
#define _TKSIAZKA_H
#include <string>
using namespace std;
class TStrona;
class TKsiazka {
public:
	TKsiazka();
	~TKsiazka();
	void setTytul(string tTytul);
	string getTytul();
	void setAutor(string tAutor);
	string getAutor();
	void printData();
	void setData(int tNrStrony);
private:
	TStrona* strona;
	string tytul;
	string autor;
};

#endif  //_TKSIAZKA_H
