//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TStrona.cpp
//  @ Date : 05.04.2024
//  @ Author : 
//
//

#include "TStrona.h"
#include <iostream>
using namespace std;

TStrona::TStrona() {
    cout << "Konstruktor klasy TStrona." << endl;
}

TStrona::~TStrona() {
    cout << "Destruktor klasy TStrona." << endl;
}

void TStrona::setNrStrony(int tNrStrony) {
    nrStrony = tNrStrony;
}

int TStrona::getNrStrony() {
    return nrStrony;
}

