//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TKsiazka.cpp
//  @ Date : 19.03.2024
//  @ Author : 
//
//


#include "TKsiazka.h"
#include <iostream>
#include "TStrona.h"
using namespace std;

TKsiazka::TKsiazka(string tTytul) {
    tytul = tTytul;
}

TKsiazka::~TKsiazka() {

}

void TKsiazka::printData() {
    cout << strona->getNrStrony() << endl;
}

void TKsiazka::setData(int tNrStrony) {
    strona->setNrStrony(tNrStrony);
}

