//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TStrona.h
//  @ Date : 19.03.2024
//  @ Author : 
//
//


#if !defined(_TSTRONA_H)
#define _TSTRONA_H


class TStrona {
public:
	TStrona();
	~TStrona();
	void setNrStrony(int tNrStrony);
	int getNrStrony();
private:
	int nrStrony;
};

#endif  //_TSTRONA_H
