//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Autor.cpp
//  @ Date : 17.03.2024
//  @ Author : 
//
//


#include "Autor.h"
#include <string>

using namespace std;

void Autor::setKsiazka(Ksiazka* ksiazka) {
    tKsiazka = ksiazka;
}

void Autor::setImie(string imie) {
    tImie = imie;
}

void Autor::setNazwisko(string nazwisko) {
    tNazwisko = nazwisko;
}

Ksiazka* Autor::getKsiazka() {
    return tKsiazka;
}

string Autor::getImie() {
    return tImie;
}

string Autor::getNazwisko() {
    return tNazwisko;
}

