//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ksiazka.cpp
//  @ Date : 17.03.2024
//  @ Author : 
//
//


#include "Ksiazka.h"
#include <string>

using namespace std;


void Ksiazka::setAutor(Autor* autor) {
    tAutor = autor;
}

void Ksiazka::setTytul(string tytul) {
    tTytul = tytul;
}

string Ksiazka::getTytul() {
    return tTytul;
}

Autor* Ksiazka::getAutor() {
    return tAutor;
}

