//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ksiazka.h
//  @ Date : 17.03.2024
//  @ Author : 
//
//


#if !defined(_KSIAZKA_H)
#define _KSIAZKA_H
#include <string>
using namespace std;

class Autor;

class Ksiazka {
public:
	void setAutor(Autor* autor);
	void setTytul(string tytul);
	string getTytul();
	Autor* getAutor();
private:
	Autor* tautor;
	string ttytul;
};

#endif  //_KSIAZKA_H
