//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Zeszyt.h
//  @ Date : 12.03.2024
//  @ Author : 
//
//


#if !defined(_ZESZYT_H)
#define _ZESZYT_H
#include <string>
using namespace std;

class Zeszyt {
public:
	int Ilosc_kartek;
	string Kolor;
	Zeszyt();
	~Zeszyt();
};

#endif  
