//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CheesePizza.h
//  @ Date : 11.06.2024
//  @ Author : 
//
//


#if !defined(_CHEESEPIZZA_H)
#define _CHEESEPIZZA_H

#include "Pizza.h"

class CheesePizza : public Pizza {
public:
	CheesePizza();
	~CheesePizza();
	void printPizza();
	Pizza clone();
	Pizza clone();
};

#endif  //_CHEESEPIZZA_H
