//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CheesePizza.cpp
//  @ Date : 11.06.2024
//  @ Author : 
//
//


#include "CheesePizza.h"
#include "Pizza.h"

CheesePizza::CheesePizza() {

}

CheesePizza::~CheesePizza() {

}

void CheesePizza::printPizza() {

}

Pizza CheesePizza::clone() {

}

Pizza CheesePizza::clone() {

}

