//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HawaiiPizza.h
//  @ Date : 11.06.2024
//  @ Author : 
//
//


#if !defined(_HAWAIIPIZZA_H)
#define _HAWAIIPIZZA_H

#include "Pizza.h"

class HawaiiPizza : public Pizza {
public:
	HawaiiPizza();
	~HawaiiPizza();
	void printPizza();
	Pizza clone();
	Pizza clone();
};

#endif  //_HAWAIIPIZZA_H
