//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : HawaiiPizza.cpp
//  @ Date : 11.06.2024
//  @ Author : 
//
//


#include "HawaiiPizza.h"
#include "Pizza.h"

HawaiiPizza::HawaiiPizza() {

}

HawaiiPizza::~HawaiiPizza() {

}

void HawaiiPizza::printPizza() {

}

Pizza HawaiiPizza::clone() {

}

Pizza HawaiiPizza::clone() {

}

