//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pizza.cpp
//  @ Date : 11.06.2024
//  @ Author : 
//
//


#include "Pizza.h"
#include "PizzaType.h"

Pizza::Pizza(PizzaType type) {

}

Pizza::~Pizza() {

}

void Pizza::printPizza() {

}

PizzaType Pizza::getType() {

}

