//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : PizzaFactory.cpp
//  @ Date : 11.06.2024
//  @ Author : 
//
//


#include "PizzaFactory.h"
#include "Pizza.h"
#include "PizzaType.h"

PizzaFactory PizzaFactory::Instance() {

}

PizzaFactory::~PizzaFactory() {

}

Pizza PizzaFactory::createPizza(PizzaType type) {

}

PizzaFactory::PizzaFactory() {

}

