//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pizza.h
//  @ Date : 11.06.2024
//  @ Author : 
//
//


#if !defined(_PIZZA_H)
#define _PIZZA_H

#include "PizzaType.h"

class Pizza {
public:
	Pizza(PizzaType type);
	~Pizza();
	virtual Pizza clone() = 0;
	void printPizza();
	PizzaType getType();
};

#endif  //_PIZZA_H
