//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : PizzaFactory.h
//  @ Date : 11.06.2024
//  @ Author : 
//
//


#if !defined(_PIZZAFACTORY_H)
#define _PIZZAFACTORY_H

#include "Pizza.h"
#include "PizzaType.h"

class PizzaFactory {
public:
	static PizzaFactory Instance();
	~PizzaFactory();
	Pizza createPizza(PizzaType type);
private:
	map<PizzaType, Pizza*> prototypes;
	PizzaFactory();
};

#endif  //_PIZZAFACTORY_H
