//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : PizzaType.h
//  @ Date : 11.06.2024
//  @ Author : 
//
//


#if !defined(_PIZZATYPE_H)
#define _PIZZATYPE_H

#include "Pizza.h"

class PizzaType {
public:
	int Cheese;
	int Hawaii;
	Pizza *prototype;
};

#endif  //_PIZZATYPE_H
