//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Biblioteka.h
//  @ Date : 17.03.2024
//  @ Author : 
//
//


#if !defined(_BIBLIOTEKA_H)
#define _BIBLIOTEKA_H

#include "Ksiazka.h"
#include <string>
using namespace std;

class Biblioteka {
public:
	Biblioteka(string kNazwa);
	void printData();
	void setData(string kTytul, string kAutor);
private:
	string nazwa;
	Ksiazka tKsiazka;
};

#endif  //_BIBLIOTEKA_H
