//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Biblioteka.h
//  @ Date : 17.03.2024
//  @ Author : 
//
//


#if !defined(_BIBLIOTEKA_H)
#define _BIBLIOTEKA_H

#include "Ksiazka.h"
#include <string>
using namespace std;

class Biblioteka {
public:
	Biblioteka(string knazwa);
	void printData();
	void setData(string k_tytul, string k_autor);
private:
	string nazwa;
	Ksiazka tksiazka;
};

#endif  //_BIBLIOTEKA_H
