//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Biblioteka.cpp
//  @ Date : 17.03.2024
//  @ Author : 
//
//

#include <iostream>
#include "Biblioteka.h"
#include <string>
using namespace std;
Biblioteka::Biblioteka(string knazwa) {
    nazwa = knazwa;
}

void Biblioteka::printData() {
    cout << tksiazka.getAutor() << endl;
    cout << tksiazka.getTytul() << endl;
}

void Biblioteka::setData(string k_tytul, string k_autor) {
    tksiazka.setAutor(k_autor);
    tksiazka.setTytul(k_tytul);
}

