//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ksiazka.cpp
//  @ Date : 17.03.2024
//  @ Author : 
//
//


#include "Ksiazka.h"
#include <string>
using namespace std;
void Ksiazka::setAutor(string kAutor) {
    autor = kAutor;
}

void Ksiazka::setTytul(string kTytul) {
    tytul = kTytul;
}

string Ksiazka::getAutor() {
    return autor;
}

string Ksiazka::getTytul() {
    return tytul;
}

