//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Dolar.cpp
//  @ Date : 04.06.2024
//  @ Author : 
//
//


#include "Dolar.h"

Dolar::Dolar(double kwotaWZlotym):Strategia(kwotaWZlotym){}
    


void Dolar::count() {
    cout << "Zamiana zlotych na dolara: "<< kwotaWZlotym*0.25 << " dolarow." << endl;
}



