//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Dolar.h
//  @ Date : 04.06.2024
//  @ Author : 
//
//


#if !defined(_DOLAR_H)
#define _DOLAR_H

#include "Strategia.h"
#include <iostream>
using namespace std;
class Dolar : public Strategia {
public:
	Dolar(double kwotaWZlotym);
private:
	void count();
};

#endif  //_DOLAR_H
