//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Euro.cpp
//  @ Date : 04.06.2024
//  @ Author : 
//
//


#include "Euro.h"

Euro::Euro(double kwotaWZlotym):Strategia(kwotaWZlotym) {

}

void Euro::count() {
    cout << "Zamiana zlotych na euro: "<< kwotaWZlotym*0.23 << " euro." << endl;
}



