//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Euro.h
//  @ Date : 04.06.2024
//  @ Author : 
//
//


#if !defined(_EURO_H)
#define _EURO_H

#include "Strategia.h"
#include <iostream>
using namespace std;
class Euro : public Strategia {
public:
	Euro(double kwotaWZlotym);
private:
	void count();
};

#endif  //_EURO_H
