//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Frank.cpp
//  @ Date : 04.06.2024
//  @ Author : 
//
//


#include "Frank.h"

Frank::Frank(double kwotaWZlotym):Strategia(kwotaWZlotym) {

}

void Frank::count() {
    cout << "Zamiana zlotych na frank: "<< kwotaWZlotym*0.22 << " frankow."<< endl;
}


