//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Frank.h
//  @ Date : 04.06.2024
//  @ Author : 
//
//


#if !defined(_FRANK_H)
#define _FRANK_H

#include "Strategia.h"
#include <iostream>
using namespace std;

class Frank : public Strategia {
public:
	Frank(double kwotaWZlotym);
private:
	void count();
};

#endif  //_FRANK_H
