//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jen.cpp
//  @ Date : 04.06.2024
//  @ Author : 
//
//


#include "Jen.h"

Jen::Jen(double kwotaWZlotym):Strategia(kwotaWZlotym) {

}

void Jen::count() {
    cout << "Zamiana zlotych na jen: "<< kwotaWZlotym*0.026 << endl;
}



