//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jen.h
//  @ Date : 04.06.2024
//  @ Author : 
//
//


#if !defined(_JEN_H)
#define _JEN_H

#include "Strategia.h"
#include <iostream>
using namespace std;
class Jen : public Strategia {
public:
	Jen(double kwotaWZlotym);
private:
	void count();
};

#endif  //_JEN_H
