//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : NaliczanieOprocentowania.h
//  @ Date : 04.06.2024
//  @ Author : 
//
//


#if !defined(_NALICZANIEOPROCENTOWANIA_H)
#define _NALICZANIEOPROCENTOWANIA_H

#include "Strategia.h"
#include "Frank.h"
#include "Euro.h"
#include "Jen.h"
#include "Dolar.h"
#include <iostream>
class NaliczanieOprocentowania {
public:
	NaliczanieOprocentowania();
	void setStrategia(int typ, double kwotaWZlotym);
	void contexInterface();
	Strategia *strategy;
private:
	Strategia* strategia;
};

#endif  //_NALICZANIEOPROCENTOWANIA_H
