//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : NaliczanieOprocentowania.cpp
//  @ Date : 04.06.2024
//  @ Author : 
//
//


#include "NaliczanieOprocentowania.h"

NaliczanieOprocentowania::NaliczanieOprocentowania() {
    strategia = nullptr;
}

void NaliczanieOprocentowania::setStrategia(int typ, double kwotaWZlotym) {
    if(typ == 1) strategia = new Frank(kwotaWZlotym);
        else if(typ == 2) strategia = new Euro(kwotaWZlotym);
            else if(typ == 3) strategia = new Jen(kwotaWZlotym);
                else if(typ == 4) strategia = new Dolar(kwotaWZlotym);
}

void NaliczanieOprocentowania::contexInterface() {
    strategia->result();
}

