//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Strategia.h
//  @ Date : 04.06.2024
//  @ Author : 
//
//


#if !defined(_STRATEGIA_H)
#define _STRATEGIA_H


class Strategia {
public:
	Strategia(int kwota);
	virtual ~Strategia(){}
protected:
	double kwotaWZlotym;
	void result();
private:
	virtual void count() = 0;
};

#endif  //_STRATEGIA_H
