//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Strategia.cpp
//  @ Date : 04.06.2024
//  @ Author : 
//
//


#include "Strategia.h"

Strategia::Strategia(int kwota) {
    kwotaWZlotym = kwota;
}

void Strategia::result() {
    count();
}

