//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.h
//  @ Date : 12.03.2024
//  @ Author : 
//
//


#if !defined(_STUDENT_H)
#define _STUDENT_H
#include <string>
#include "Zeszyt.h"
using namespace std;

class Student {
public:
	string Imie;
	string Nazwisko;
	Zeszyt UzyjZeszytu(Zeszyt zeszyt);
};

#endif  //_STUDENT_H
