//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.cpp
//  @ Date : 12.03.2024
//  @ Author : 
//
//


#include "Student.h"
#include "Zeszyt.h"

Zeszyt Student::UzyjZeszytu(Zeszyt zeszyt) {
    zeszyt.Ilosc_kartek = 60;
    zeszyt.Kolor = "red";
    return zeszyt;
    
}

