//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Zeszyt.cpp
//  @ Date : 12.03.2024
//  @ Author : 
//
//


#include "Zeszyt.h"
#include <string>
using namespace std;
Zeszyt::Zeszyt() {

}

Zeszyt::~Zeszyt() {

}

