//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Client.h
//  @ Date : 02.06.2024
//  @ Author : 
//
//


#if !defined(_CLIENT_H)
#define _CLIENT_H


class Client {
};

#endif  //_CLIENT_H
