//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IDeviceFactory.cpp
//  @ Date : 02.06.2024
//  @ Author : 
//
//


#include "IDeviceFactory.h"

IPCDevice* IDeviceFactory::fPCDevice() {

}

ILaptopDevice* IDeviceFactory::fLaptopDevice() {

}

