//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IDeviceFactory.h
//  @ Date : 02.06.2024
//  @ Author : 
//
//


#if !defined(_IDEVICEFACTORY_H)
#define _IDEVICEFACTORY_H


class IDeviceFactory {
private:
	IPCDevice* fPCDevice();
	ILaptopDevice* fLaptopDevice();
};

#endif  //_IDEVICEFACTORY_H
