//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IDeviceFactory.h
//  @ Date : 02.06.2024
//  @ Author : 
//
//


#if !defined(_IDEVICEFACTORY_H)
#define _IDEVICEFACTORY_H

class IPCDevice;
class ILaptopDevice;

class IDeviceFactory {


public:
    virtual ~IDeviceFactory() {}
    virtual IPCDevice* fPCDevice() = 0;
    virtual ILaptopDevice* fLaptopDevice() = 0;
};

#endif  //_IDEVICEFACTORY_H
