//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IPCDevice.h
//  @ Date : 02.06.2024
//  @ Author : 
//
//


#if !defined(_IPCDEVICE_H)
#define _IPCDEVICE_H


class IPCDevice {
public:
	void displayDevice();
};

#endif  //_IPCDEVICE_H
