//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IPCDevice.cpp
//  @ Date : 02.06.2024
//  @ Author : 
//
//


#include "IPCDevice.h"

void IPCDevice::displayDevice() {

}

