//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : THHDDeviceFactory.h
//  @ Date : 02.06.2024
//  @ Author : 
//
//


#if !defined(_THHDDEVICEFACTORY_H)
#define _THHDDEVICEFACTORY_H

#include "IDeviceFactory.h"
#include "TPCHDDevice.h"
#include "TLaptopHDDDevice.h"

class THHDDeviceFactory : public IDeviceFactory {
public:
	IPCDevice* fPCDevice();
	ILaptopDevice* fLaptopDevice();

};

#endif  //_THHDDEVICEFACTORY_H
