//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : THHDDeviceFactory.cpp
//  @ Date : 02.06.2024
//  @ Author : 
//
//


#include "THHDDeviceFactory.h"

IPCDevice* THHDDeviceFactory::fPCDevice() {
    return new TPCHDDevice();
}

ILaptopDevice* THHDDeviceFactory::fLaptopDevice() {
    return new TLaptopHDDDevice();
}

