//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : THHDDeviceFactory.h
//  @ Date : 02.06.2024
//  @ Author : 
//
//


#if !defined(_THHDDEVICEFACTORY_H)
#define _THHDDEVICEFACTORY_H

#include "IDeviceFactory.h"

class THHDDeviceFactory : public IDeviceFactory, public IDeviceFactory {
public:
	IPCDevice* fPCDevice();
	ILaptopDevice* Operation2();
};

#endif  //_THHDDEVICEFACTORY_H
