//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TLaptopSSDDevice.cpp
//  @ Date : 02.06.2024
//  @ Author : 
//
//


#include "TLaptopSSDDevice.h"


void TLaptopSSDDevice::displayDevice() {
    cout << "Laptop SSD Device" << endl;
}

