//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TLaptopSSDDevice.h
//  @ Date : 02.06.2024
//  @ Author : 
//
//


#if !defined(_TLAPTOPSSDDEVICE_H)
#define _TLAPTOPSSDDEVICE_H

#include "ILaptopDevice.h"
#include <iostream>
using namespace std;
class TLaptopSSDDevice : public ILaptopDevice {

private:
	void displayDevice();
};

#endif  //_TLAPTOPSSDDEVICE_H
