//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TLaptopHDDDevice.h
//  @ Date : 02.06.2024
//  @ Author : 
//
//


#if !defined(_TLAPTOPHDDDEVICE_H)
#define _TLAPTOPHDDDEVICE_H

#include "ILaptopDevice.h"
#include <iostream>
using namespace std;
class TLaptopHDDDevice : public ILaptopDevice{

private:
	void displayDevice();
};

#endif  //_TLAPTOPHDDDEVICE_H
