//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TLaptopHDDDevice.cpp
//  @ Date : 02.06.2024
//  @ Author : 
//
//


#include "TLaptopHDDDevice.h"


void TLaptopHDDDevice::displayDevice() {
    cout << "Laptop HDD Device" << endl;
}

