//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TLaptopHDDDevice.h
//  @ Date : 02.06.2024
//  @ Author : 
//
//


#if !defined(_TLAPTOPHDDDEVICE_H)
#define _TLAPTOPHDDDEVICE_H

#include "ILaptopDevice.h"

class TLaptopHDDDevice : public ILaptopDevice, public ILaptopDevice {
public:
	void displayDevice();
private:
	void displayDevice();
};

#endif  //_TLAPTOPHDDDEVICE_H
