//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TPCHDDevice.cpp
//  @ Date : 02.06.2024
//  @ Author : 
//
//


#include "TPCHDDevice.h"

void TPCHDDevice::displayDevice() {

}

