//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TPCHDDevice.h
//  @ Date : 02.06.2024
//  @ Author : 
//
//


#if !defined(_TPCHDDEVICE_H)
#define _TPCHDDEVICE_H

#include "IPCDevice.h"

class TPCHDDevice : public IPCDevice, public IPCDevice {
private:
	void displayDevice();
};

#endif  //_TPCHDDEVICE_H
