//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TPCSSDDevice.h
//  @ Date : 02.06.2024
//  @ Author : 
//
//


#if !defined(_TPCSSDDEVICE_H)
#define _TPCSSDDEVICE_H

#include "IPCDevice.h"
#include <iostream>
using namespace std;
class TPCSSDDevice : public IPCDevice {
private:
	void displayDevice();
};

#endif  //_TPCSSDDEVICE_H
