//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TPCSSDDevice.cpp
//  @ Date : 02.06.2024
//  @ Author : 
//
//


#include "TPCSSDDevice.h"

void TPCSSDDevice::displayDevice() {

}

