//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TSSDDeviceFactory.h
//  @ Date : 02.06.2024
//  @ Author : 
//
//


#if !defined(_TSSDDEVICEFACTORY_H)
#define _TSSDDEVICEFACTORY_H

#include "IDeviceFactory.h"

class TSSDDeviceFactory : public IDeviceFactory, public IDeviceFactory {
public:
	IPCDevice* fPCDevice();
	ILaptopDevice* fLaptopDevice();
};

#endif  //_TSSDDEVICEFACTORY_H
