//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TSSDDeviceFactory.cpp
//  @ Date : 02.06.2024
//  @ Author : 
//
//


#include "TSSDDeviceFactory.h"

IPCDevice* TSSDDeviceFactory::fPCDevice() {

}

ILaptopDevice* TSSDDeviceFactory::fLaptopDevice() {

}

