//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.cpp
//  @ Date : 05.03.2024
//  @ Author : 
//
//

#include <iostream>
#include "Jamnik.h"
using namespace std;
Jamnik::Jamnik(float dlugosc, string umaszczenie) { //tutaj jest cos zle z klasa dziedziczaca program nie czai ze tu jest dziedziczenie i jak tu zrobic konstruktor
    Ssak::Ssak(); //nwm cos takieg? inheritance c++ poszukac poprawic bo to JAKAS MASAKRA
    // this->dlugosc = dlugosc;
    // this->umaszczenie = umaszczenie;
}

Jamnik::~Jamnik() {

}

void Jamnik::ustawDlugosc(float dlugosc) {
    this->dlugosc = dlugosc;
}

void Jamnik::ustawUmaszczenie(string umaszczenie) {
    this->umaszczenie = umaszczenie;
}

float Jamnik::pokazDlugosc() {
    return dlugosc;
}

string Jamnik::pokazUmaszczenie() {
    return umaszczenie;
}

void Jamnik::kop() {
    cout << "Jamnik kopie." << endl;
}

void Jamnik::trop() {
    cout << "Jamnik tropi." << endl;
}

