//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.cpp
//  @ Date : 05.03.2024
//  @ Author : 
//
//

#include <iostream>
#include "Jamnik.h"
using namespace std;
Jamnik::Jamnik(float dlugosc, string umaszczenie) : Pies("", 0) {
    this->dlugosc = dlugosc;
    this->umaszczenie = umaszczenie;
}
Jamnik::~Jamnik() {

}

Jamnik::Jamnik() : Pies("", 0) {
}

void Jamnik::ustawDlugosc(float dlugosc) {
    this->dlugosc = dlugosc;
}

void Jamnik::ustawUmaszczenie(string umaszczenie) {
    this->umaszczenie = umaszczenie;
}

float Jamnik::pokazDlugosc() {
    return dlugosc;
}

string Jamnik::pokazUmaszczenie() {
    return umaszczenie;
}

void Jamnik::kop() {
    cout << "Jamnik kopie." << endl;
}

void Jamnik::trop() {
    cout << "Jamnik tropi." << endl;
}

