//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.h
//  @ Date : 05.03.2024
//  @ Author : 
//
//


#if !defined(_PIES_H)
#define _PIES_H
#include <string>
#include "Ssak.h"
using namespace std;
class Pies : public Ssak {
public:
	Pies(string rasa, float waga);
	~Pies();
	Pies();
	void ustawRase(string rasa);
	void ustawWage(float waga);
	string pokazRase();
	float pokazWage();
	void biegaj();
	void szczekaj();
protected:
	string rasa;
	float waga;
};

#endif  //_PIES_H
