//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.h
//  @ Date : 05.03.2024
//  @ Author : 
//
//


#if !defined(_SSAK_H)
#define _SSAK_H
#include <string>
using namespace std;
class Ssak {
public:
	Ssak(string plec, int wiek);
	~Ssak();
	void ustawWiek(int wiek);
	void ustawPlec(string plec);
	int pokazWiek();
	string pokazPlec();
	void oddychaj();
	void jedz();
protected:
	string plec;
	int wiek;
};

#endif  //_SSAK_H
