//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.cpp
//  @ Date : 05.03.2024
//  @ Author : 
//
//


#include "Ssak.h"
#include <iostream>
using namespace std;
Ssak::Ssak(string plec, int wiek) {
    this->plec = plec;
    this->wiek = wiek;
}

Ssak::~Ssak() {
}

void Ssak::ustawWiek(int wiek) {
    this->wiek = wiek;
}

void Ssak::ustawPlec(string plec) {
    this->plec = plec;
}

int Ssak::pokazWiek() {
    return wiek;
}

string Ssak::pokazPlec() {
    return plec;
}

void Ssak::oddychaj() {
    cout << "Ssak oddycha." << endl;
}

void Ssak::jedz() {
    cout << "Ssak je." << endl;
}

