//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Human.cpp
//  @ Date : 22.03.2024
//  @ Author : 
//
//

#include "Human.h"

Human::Human() {

}

Human::~Human() {

}

void Human::setAge(int humanAge) {
    age = humanAge;
}

void Human::setGender(string humanGender) {
    gender = humanGender;
}

int Human::getAge() {
    return age;
}

string Human::getGender() {
    return gender;
}

