//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Human.h
//  @ Date : 22.03.2024
//  @ Author : 
//
//


#if !defined(_HUMAN_H)
#define _HUMAN_H
#include <string>

using namespace std;

class Human {
public:
	Human();
	~Human();
	void setAge(int humanAge);
	void setGender(string humanGender);
	int getAge();
	string getGender();
private:
	int age;
	string gender;
};

#endif  //_HUMAN_H
