//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Human.cpp
//  @ Date : 22.03.2024
//  @ Author : 
//
//

#include "Human.h"

Human::Human() {

}

Human::~Human() {

}

void Human::setAge(int humanAge) {

}

void Human::setGender(int humanGender) {

}

int Human::getAge() {

}

string Human::getGender() {

}

