//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.h
//  @ Date : 22.03.2024
//  @ Author : 
//
//


#if !defined(_STUDENT_H)
#define _STUDENT_H

#include "Human.h"
#include <string>

using namespace std;

class Student : public Human {
public:
	Student();
	~Student();
	void setIndexNr(int studentIndexNr);
	void setName(string studentName);
	int getIndexNr();
	string getName();
private:
	int indexNr;
	string name;
};

#endif  //_STUDENT_H
