//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.cpp
//  @ Date : 22.03.2024
//  @ Author : 
//
//


#include "Student.h"

Student::Student() {

}

Student::~Student() {

}

void Student::setIndexNr(int studentIndexNr) {
    indexNr = studentIndexNr;
}

void Student::setName(string studentName) {
    name = studentName;
}

int Student::getIndexNr() {
    return indexNr;
}

string Student::getName() {
    return name;
}

