//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : University.cpp
//  @ Date : 22.03.2024
//  @ Author : 
//
//

#include "Student.h"
#include "University.h"
#include <iostream>

using namespace std;

void University::attach(Student* mStudent) {
    students.push_back(mStudent);
}

void University::detach() {
    students.pop_back();
}

void University::printData(int i) {
    cout << students[i]->getIndexNr() << ", " << students[i]->getName() << ", " << students[i]->getAge() << ", " << students[i]->getGender() << endl;

}

void University::setData(int i, string studentName, int studentIndexNr, string studentGender, int studentAge) {
    students[i]->setIndexNr(studentIndexNr);
    students[i]->setName(studentName);
    students[i]->setAge(studentAge);
    students[i]->setGender(studentGender);
}

void University::setName(string universityName) {
    name = universityName;
}

string University::getName() {
    return name;
}

