//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : University.h
//  @ Date : 22.03.2024
//  @ Author : 
//
//


#if !defined(_UNIVERSITY_H)
#define _UNIVERSITY_H

#include <string>
#include <vector>


class Student;

using namespace std;

class University {
public:
	void attach(Student* mStudent);
	void detach();
	void printData(int i);
	void setData(int i, string studentName, int studentIndexNr);
	void setName(string universityName);
	string getName();
private:
	string name;
	vector<Student*> students;
};

#endif  //_UNIVERSITY_H
