//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Folder.cpp
//  @ Date : 19.03.2024
//  @ Author : 
//
//


#include "Folder.h"

void Folder::attach(Plik* tPlik) {

}

void Folder::detach() {

}

void Folder::printData(int i) {

}

void Folder::setData(int i, string nazwa, string format) {

}

