//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Folder.h
//  @ Date : 19.03.2024
//  @ Author : 
//
//


#if !defined(_FOLDER_H)
#define _FOLDER_H
#include <string>
#include <vector>
using namespace std;
class Plik;


class Folder {
public:
	void attach(Plik* tPlik);
	void detach();
	void printData(int i);
	void setData(int i, string nazwa, string format);
private:
	vector<Plik*> pliki;
};

#endif  //_FOLDER_H
