//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Folder.cpp
//  @ Date : 19.03.2024
//  @ Author : 
//
//

#include "Plik.h"
#include "Folder.h"
#include <iostream>
using namespace std;

void Folder::attach(Plik* tPlik) {
    pliki.push_back(tPlik);
}

void Folder::detach() {
    pliki.pop_back();
}

void Folder::printData(int i) {
    cout << pliki[i]->getNazwa() << " " << pliki[i]->getFormat() << endl;
}

void Folder::setData(int i, string nazwa, string format) {
    pliki[i]->setNazwa(nazwa);
    pliki[i]->setFormat(format);
}

