//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Plik.h
//  @ Date : 19.03.2024
//  @ Author : 
//
//


#if !defined(_PLIK_H)
#define _PLIK_H
#include <string>
using namespace std;
class Plik {
public:
	Plik();
	~Plik();
	void setNazwa(string tNazwa);
	void setFormat(string tFormat);
	string getNazwa();
	string getFormat();
private:
	string nazwa;
	string format;
};

#endif  //_PLIK_H
