//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Plik.cpp
//  @ Date : 19.03.2024
//  @ Author : 
//
//


#include "Plik.h"

Plik::Plik() {

}

Plik::~Plik() {

}

void Plik::setNazwa(string tNazwa) {
    nazwa = tNazwa;
}

void Plik::setFormat(string tFormat) {
    format = tFormat;
}

string Plik::getNazwa() {
    return nazwa;
}

string Plik::getFormat() {
    return format;
}

