//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : potega.cpp
//  @ Date : 16.04.2024
//  @ Author : 
//
//


#include "potega.h"

float potega::obliczQ(float podstawa, int wykladnikK, int wykladnikN) {

}

float potega::obliczP(float podstawa, int wykladnikK) {

}

