//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Potega.cpp
//  @ Date : 18.04.2024
//  @ Author : 
//
//


#include "Potega.h"

double Potega::obliczPotege(double oPodstawa, int oWykladnik) {
    podstawa = oPodstawa;
    wykladnik = oWykladnik;
    double wynik = 1;
    for (int i = 0; i < wykladnik; i++) {
        wynik *= podstawa;
    }
    return wynik;
}

