//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Potega.h
//  @ Date : 18.04.2024
//  @ Author : 
//
//


#if !defined(_POTEGA_H)
#define _POTEGA_H


class Potega {
public:
	double obliczPotege(double oPodstawa, int oWykladnik);
private:
	double podstawa;
	int wykladnik;
};

#endif  //_POTEGA_H
