//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : potega.h
//  @ Date : 16.04.2024
//  @ Author : 
//
//


#if !defined(_POTEGA_H)
#define _POTEGA_H


class potega {
public:
	float obliczQ(float podstawa, int wykladnikK, int wykladnikN);
	float obliczP(float podstawa, int wykladnikK);
private:
	float podstawa;
	int wykladnikK;
	int wykladnikN;
};

#endif  //_POTEGA_H
