//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prawdopodobienstwo.cpp
//  @ Date : 18.04.2024
//  @ Author : 
//
//


#include "Prawdopodobienstwo.h"
#include "SymbolNewtona.h"
#include "Potega.h"

double Prawdopodobienstwo::obliczPrawdopodobienstwo(int k, int n, float p) {
    kSymbolNewtona = new SymbolNewtona();
    kPotega = new Potega();
    p = p;
    q = 1 - p;
    return kSymbolNewtona->obliczSymbolNewtona(n, k) * kPotega->obliczPotege(p, k) * kPotega->obliczPotege(q, n - k);
}

