//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prawdopodobienstwo.h
//  @ Date : 16.04.2024
//  @ Author : 
//
//


#if !defined(_PRAWDOPODOBIENSTWO_H)
#define _PRAWDOPODOBIENSTWO_H


class prawdopodobienstwo {
public:
	float obliczPrawdopodobienstwo(int kSymbolNewtona, int kPotegaJeden, int kPotegaDwa);
private:
	symbolNewtona* kSymbolNewtona;
	potega* kPotegaJeden;
	potega* kPotegaDwa;
};

#endif  //_PRAWDOPODOBIENSTWO_H
