//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prawdopodobienstwo.cpp
//  @ Date : 16.04.2024
//  @ Author : 
//
//


#include "prawdopodobienstwo.h"

float prawdopodobienstwo::obliczPrawdopodobienstwo(int kSymbolNewtona, int kPotegaJeden, int kPotegaDwa) {

}

