//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Silnia.cpp
//  @ Date : 18.04.2024
//  @ Author : 
//
//


#include "Silnia.h"

double Silnia::obliczSilnie(int liczba) {
    double wynik = 1;
    for (int i = 1; i <= liczba; i++) {
        wynik *= i;
    }
    return wynik;
}

