//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : silnia.cpp
//  @ Date : 16.04.2024
//  @ Author : 
//
//


#include "silnia.h"

int silnia::obliczSilnie(int liczba) {

}

