//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : silnia.h
//  @ Date : 16.04.2024
//  @ Author : 
//
//


#if !defined(_SILNIA_H)
#define _SILNIA_H


class silnia {
public:
	int obliczSilnie(int liczba);
private:
	int liczba;
};

#endif  //_SILNIA_H
