//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Silnia.h
//  @ Date : 18.04.2024
//  @ Author : 
//
//


#if !defined(_SILNIA_H)
#define _SILNIA_H


class Silnia {
public:
	double obliczSilnie(int liczba);
private:
	int liczba;
};

#endif  //_SILNIA_H
