//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SymbolNewtona.cpp
//  @ Date : 18.04.2024
//  @ Author : 
//
//


#include "SymbolNewtona.h"
#include "Silnia.h"

double SymbolNewtona::obliczSymbolNewtona(int n, int k) {
    silniaK = new Silnia();
    roznica = n - k;
    if (k == 0 || k == n) {
        return 1;
    } else {
        return silniaK->obliczSilnie(n) / (silniaK->obliczSilnie(k) * silniaK->obliczSilnie(roznica));
    }
}

