//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : symbolNewtona.cpp
//  @ Date : 16.04.2024
//  @ Author : 
//
//


#include "symbolNewtona.h"

int symbolNewtona::obliczSymbolNewtona(int silniaN, int silniaK, int silniaRoznicy) {

}

