//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : symbolNewtona.h
//  @ Date : 16.04.2024
//  @ Author : 
//
//


#if !defined(_SYMBOLNEWTONA_H)
#define _SYMBOLNEWTONA_H


class symbolNewtona {
public:
	int obliczSymbolNewtona(int silniaN, int silniaK, int silniaRoznicy);
private:
	silnia* silniaN;
	silnia* silniaK;
	silnia* silniaRoznicy;
};

#endif  //_SYMBOLNEWTONA_H
