//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SymbolNewtona.h
//  @ Date : 18.04.2024
//  @ Author : 
//
//

#include <iostream>
using namespace std;
#if !defined(_SYMBOLNEWTONA_H)
#define _SYMBOLNEWTONA_H
class Silnia;

class SymbolNewtona {
public:
	double obliczSymbolNewtona(int n, int k);
private:
	Silnia* silniaK;
	int roznica;
};

#endif  //_SYMBOLNEWTONA_H
